### ISSUE TITLE
[A2][SDA-2] <Sankalp Saxena> — Sample Data & Kafka Producer

### ISSUE THREAD

**Issue by 341224-blip** [aditya-dua/SDA#246]
### Section

SDA-2

### Full Name

Sankalp Saxena

### Student ID / Roll Number

341224

### Link to Your Assignment 1 Submission

https://github.com/aditya-dua/SDA/issues/56

### GitHub Repository Link

https://github.com/341224-blip/Quickcommerce_Sources.git

### Kafka Topic Name Used

Quickcommerce_Transactions

### **Order-Events**
- Format: JSON, one object per Kafka message
- Fields: order_id, event_type, order_status, order_timestamp, customer_id, dark_store_id, delivery_address, sku, product_name, quantity, cart_value, payment_method, promised_delivery_minutes
- Rows: Continuous stream — a new order roughly every 2-4 seconds, with each order producing 1-5 lifecycle events (placed → accepted → packed → picked → delivered)
- Generated Using: Python `customer_app_producer.py` with the Faker library (for names/addresses) and randomised order attributes

### Payment-Events**
- Format: JSON, one object per Kafka message
- Fields: transaction_id, order_id, payment_method, amount, status, timestamp
- Rows: Continuous stream — one new transaction roughly every 2-4 seconds, each producing 2-3 events (initiated → authorised/failed → occasional refund)
- Generated Using: Python `payment_gateway_producer.py` with randomised payment methods, amounts, and outcome probabilities

### **inventory-events**
- Format: JSON, one object per Kafka message
- Fields: dark_store_id, sku, product_name, stock_qty, reorder_threshold, event_type, last_updated_ts
- Rows: Continuous stream — one stock update roughly every 1.5-3 seconds across 8 dark stores × 8 SKUs
- Generated Using: Python `dark_store_producer.py`, maintaining an in-memory stock table that's decremented on simulated sales and periodically restocked

### **rider-location-events**
- Format: JSON, one object per Kafka message
- Fields: rider_id, order_id, lat, long, speed_kmph, status, timestamp
- Rows: Highest-frequency stream — 15 riders each publishing a GPS ping roughly every 1-2 seconds (~440 events captured in the sample run alone)
- Generated Using: Python `rider_app_producer.py`, simulating GPS drift and status transitions (available → en route to store → en route to customer → delivered)

### **returns-events**
- Format: JSON, one object per Kafka message
- Fields: order_id, event_type (CANCELLED/RETURNED), return_reason, timestamp
- Rows: Lowest-volume stream — roughly 6% of tracked orders generate a cancellation or return event
- Generated Using: Python `customer_app_producer.py`, triggered probabilistically as orders progress through their lifecycle

### Producer code description:
Four independent Python producer scripts (one per data source) share a common `config.py` that centralises the Kafka broker address and topic names. Each script uses the `kafka-python` library to serialize events as JSON and publish them with a partitioning key chosen to preserve event ordering (e.g. `order_id` so all events for one order land on the same partition).

- **customer_app_producer.py** — tracks orders in memory, publishing a new `ORDER_PLACED` event periodically, then progressing existing orders through their lifecycle (accepted → packed → picked → delivered) on later ticks, with a small random chance of cancellation/return.
- **dark_store_producer.py** — maintains an in-memory stock table per (dark_store_id, sku), decrementing stock on simulated sales, occasionally restocking, and flagging low-stock alerts when a SKU drops to its reorder threshold.
- **rider_app_producer.py** — simulates a fleet of 15 riders whose GPS coordinates drift slightly on every tick, cycling each rider through available → en route to store → en route to customer → delivered. Publishes most frequently of all four producers.
- **payment_gateway_producer.py** — publishes a payment as INITIATED, followed shortly by AUTHORISED or FAILED, with a small chance of a later REFUNDED event.

A `run_all_producers.py` launcher starts all four as separate processes simultaneously, so the full pipeline runs with a single command.

### Terminal Output (at least 10 messages)

<img width="1447" height="942" alt="Image" src="https://github.com/user-attachments/assets/40182c93-2e69-4f8d-a707-f80a54e1993e" />

### Challenges & Learnings

**Challenges and Learnings**

**Challenges faced:**

1. **Port conflict on local Kafka setup** — ZooKeeper's default port (2181) was already occupied by an older, unrelated Kafka/ZooKeeper stack (`wurstmeister` images) left running from a previous project, causing the new Docker Compose stack to fail on startup with a "port already allocated" error.

2. **kafka-python library incompatibility** — the `kafka-python` package's bundled `six` dependency is broken on newer Python versions, causing an import failure (`ModuleNotFoundError: No module named 'kafka.vendor.six.moves'`) the moment any producer tried to connect.

3. **Mixed package installation state** — after switching to the maintained fork `kafka-python-ng`, a leftover copy of the old package's files in `site-packages` caused a second, more confusing error (`ImportError: cannot import name 'KafkaProducer'`), requiring a full clean of the package directory before reinstalling.

4. **Topic name mismatch** — querying `return-events` (singular) when the topic was actually created as `returns-events` (plural) returned an `UNKNOWN_TOPIC_OR_PARTITION` error — a simple typo that looked like a bigger pipeline failure at first glance.

5. **Terminal flooded by high-frequency data** — running the console consumer with `--from-beginning` on `rider-location-events` printed 7,725 messages in seconds, scrolling past the terminal's buffer and burying earlier command history.

**Learnings:**

- Docker containers from unrelated past projects can silently conflict with new ones on shared default ports; `docker ps -a` is the first place to check before assuming a fresh setup is broken.
- Python package ecosystems around Kafka move quickly — an actively maintained fork (`kafka-python-ng`) can be a safer default than the original, unmaintained library.
- A clean `pip uninstall` doesn't always remove every trace of a package; verifying with `python -c "import kafka; print(kafka.__file__)"` is a fast way to confirm what's actually being imported.
- Kafka topic names are exact strings with no fuzzy matching — a single missing character produces an error that looks unrelated to the real cause.
- For high-throughput topics like `rider-location-events`, `--max-messages N` is the right tool for spot-checking data, while `--from-beginning` should be reserved for genuinely wanting the full history.

[341224_Sankalp Saxena_Assignment2_SDA2.docx](https://github.com/user-attachments/files/31704248/341224_Sankalp.Saxena_Assignment2_SDA2.docx)

### Submission Checklist

- [x] I have selected my section (SDA-1 / SDA-2 / SDA-G) above and updated the issue title
- [x] My producer.py runs without errors and sends data to Kafka
- [x] I have included sample data (CSV or JSON file) in my repo
- [x] My repo is public (or I have shared access with faculty)
- [x] My submission builds directly on the industry chosen in Assignment 1
- [x] I have read and followed academic honesty guidelines
